{
 "title": "1.1 Overview / Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,unique_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview/Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{unique_cluster_name=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{unique_cluster_name=~\"$Cluster\"})"
    }
   ]
  },
  {
   "title": "Node Request Memory Average Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_memory_bytes{unique_cluster_name=~\"$Cluster\"})by (node)/sum(kube_node_status_capacity_memory_bytes{unique_cluster_name=~\"$Cluster\"})by(node))"
    }
   ]
  },
  {
   "title": "Node Request CPU Average Percent",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kube_pod_container_resource_requests_cpu_cores)by (node)/sum(kube_node_status_capacity_cpu_cores)by(node))"
    }
   ]
  },
  {
   "title": "API Server Success Request Percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(apiserver_request_total{code=~\"20.*\",verb=~\"GET|LIST\",unique_cluster_name=~\"$Cluster\"}[5m]))/sum(irate(apiserver_request_total{verb=~\"GET|LIST\",unique_cluster_name=~\"$Cluster\"}[5m]))",
     "legendFormat": "APIServer"
    }
   ]
  },
  {
   "title": "Namespace Overview",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(kube_pod_info{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{unique_cluster_name=~\"$Cluster\"}) by(namespace)"
    },
    {
     "expr": "count(kube_pod_container_info{unique_cluster_name=~\"$Cluster\"}) by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{unique_cluster_name=~\"$Cluster\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{unique_cluster_name=~\"$Cluster\"}) by(namespace)",
     "legendFormat": "secret"
    },
    {
     "expr": "count(kube_deployment_created{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_created{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_job_created{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_cronjob_created{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_pod_status_ready{condition=\"false\",unique_cluster_name=~\"$Cluster\"}==1) by(namespace) - (count(kube_pod_status_phase{phase=\"Succeeded\",unique_cluster_name=~\"$Cluster\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{condition=\"false\",unique_cluster_name=~\"$Cluster\"}==1) by(namespace)"
    },
    {
     "expr": "count(kube_deployment_status_replicas_ready{}<kube_deployment_spec_replicas{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_statefulset_status_replicas_ready{}<kube_statefulset_replicas{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{unique_cluster_name=~\"$Cluster\"}>0)by(namespace)"
    },
    {
     "expr": "count(kube_job_status_failed{unique_cluster_name=~\"$Cluster\"} == 1) by (namespace)"
    },
    {
     "expr": "count(kube_daemonset_created{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_info{unique_cluster_name=~\"$Cluster\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Node Pool Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum (kube_node_labels{unique_cluster_name=~\"$Cluster\"}) by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"memory\",unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_allocatable{resource=\"cpu\",unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_spec_unschedulable==1)by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info{unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum((max(kube_pod_status_phase{phase=\"Running\",unique_cluster_name=~\"$Cluster\"}) by (pod) > 0) * on (pod) group_right() kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_memory_bytes{unique_cluster_name=~\"$Cluster\"})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_pod_info * on (pod) group_left() (sum(kube_pod_container_resource_requests_memory_bytes{unique_cluster_name=~\"$Cluster\"}) by(pod) * on (pod) group_right() (max(kube_pod_status_phase{phase=\"Running\",unique_cluster_name=~\"$Cluster\"}) by (pod) > 0)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_memory_bytes{unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum((max(kube_pod_status_phase{phase=\"Running\",unique_cluster_name=~\"$Cluster\"}) by (pod) > 0) * on (pod) group_right() kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_cpu_cores{unique_cluster_name=~\"$Cluster\"})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id) / sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum(kube_node_status_capacity_cpu_cores{unique_cluster_name=~\"$Cluster\"})by(node))by (label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() sum((max(kube_pod_status_phase{phase=\"Running\",unique_cluster_name=~\"$Cluster\"}) by (pod) > 0) * on (pod) group_right() kube_pod_info * on (pod) group_left() (sum (kube_pod_container_resource_requests_cpu_cores{unique_cluster_name=~\"$Cluster\"})by(pod)))by (node))by(label_alibabacloud_com_nodepool_id)"
    },
    {
     "expr": "sum(group(kube_node_labels{unique_cluster_name=~\"$Cluster\"})by (node,label_alibabacloud_com_nodepool_id) * on (node) group_left() count((max(kube_pod_status_phase{phase!=\"Running\",unique_cluster_name=~\"$Cluster\"}) by (pod,namespace,phase) > 0) * on (pod,namespace) group_right() group(kube_pod_info) by (pod,namespace,node)) by (node)) by (label_alibabacloud_com_nodepool_id)"
    }
   ]
  },
  {
   "title": "Node Memory Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(label_replace(topk(10, 1-(node_memory_MemAvailable_bytes{unique_cluster_name=~\"$Cluster\"} / node_memory_MemTotal_bytes{unique_cluster_name=~\"$Cluster\"})), \"node_ip\", \"$1\", \"instance\", \"(.*):(.*)\"))by(node_ip)",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\",unique_cluster_name=~\"$Cluster\"}[1m])) by (instance) / sum(rate(node_cpu_seconds_total{unique_cluster_name=~\"$Cluster\"}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(1-node_filesystem_free_bytes{mountpoint=\"/\",unique_cluster_name=~\"$Cluster\"}/node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",unique_cluster_name=~\"$Cluster\"},\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Network In (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_receive_bytes_total{unique_cluster_name=~\"$Cluster\"}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Network Out (Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(irate(node_network_transmit_bytes_total{unique_cluster_name=~\"$Cluster\"}[1m])) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Node Sockets Count(Top 10)",
   "type": "table",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(max(node_sockstat_TCP_alloc{unique_cluster_name=~\"$Cluster\"}) by (instance),\"host_ip\",\"$1\",\"instance\",\"(.*):.*\"))by(host_ip))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, sum (container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\",container !=\"\",container!=\"POD\"}) by (container))",
     "legendFormat": "WorkingSet：[Container]:{{ container }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage/Limit(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\",container!=\"\"}/(container_spec_memory_limit_bytes{unique_cluster_name=~\"$Cluster\"}!=0)) by (container, pod, namespace))",
     "legendFormat": "WorkingSet：[Container]:{{ container }}"
    }
   ]
  },
  {
   "title": "Container CPU Usage(Top10)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", unique_cluster_name=~\"$Cluster\",container !=\"\",container!=\"POD\"}[2m])) by (container))",
     "legendFormat": "Usage [Container]:{{ container}}"
    }
   ]
  },
  {
   "title": "Container Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_network_receive_bytes_total{unique_cluster_name=~\"$Cluster\",image!=\"\",name=~\"^K8S_.*\"}[2m])) by (pod))",
     "legendFormat": "Receive: [Pod]:{{pod}}"
    },
    {
     "expr": "-topk(10, sum(irate(container_network_transmit_bytes_total{unique_cluster_name=~\"$Cluster\",image!=\"\",name=~\"^K8S_.*\"}[2m])) by (pod))",
     "legendFormat": "Transmit: [Pod]:{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage/Limit (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, avg(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\",container!=\"\"}/(container_spec_memory_limit_bytes{unique_cluster_name=~\"$Cluster\"}!=0)) by (container, pod, namespace))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage (Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\",container!=\"\",container!=\"POD\"}[1m])) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Container Socket Count(Top 10)",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_sockets{unique_cluster_name=~\"$Cluster\",container!=\"\"}) by (container,pod,namespace)or on() vector(0))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  }
 ]
}