{
 "title": "1.2 Overview / Namespace Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,unique_cluster_name)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{unique_cluster_name=~\"$Cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview / Namespace Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kube_namespace_status_phase{unique_cluster_name=~\"$Cluster\",namespace=\"$Namespace\", phase=\"Active\"})",
     "legendFormat": "status"
    }
   ]
  },
  {
   "title": "High Memory Usage(>85%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(container, pod) (container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\",namespace=\"$Namespace\", container!=\"\", image!=\"\", container!=\"POD\"})/sum by(container, pod) (kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\",resource=\"memory\", namespace=\"$Namespace\"})>0.85",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "High CPU Usage(>85% ||  >1 Core)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (container, pod) (rate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\",image!=\"\", namespace=\"$Namespace\"}[2m]))/sum by(container, pod) (kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\",resource=\"cpu\", namespace=\"$Namespace\"})> 0.85",
     "legendFormat": "{{pod}}/{{container}}(Usage/Limit)"
    },
    {
     "expr": "sum by (container, pod) (rate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\",image!=\"\", namespace=\"$Namespace\"}[1m])) > 0.9",
     "legendFormat": "{{pod}}/{{container}}(Cores)"
    }
   ]
  },
  {
   "title": "High Bandwidth Usage(>1MiB/s)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{unique_cluster_name=~\"$Cluster\", image!=\"\", namespace=~\"$Namespace\"}[2m])) by (pod) > 1024*1024",
     "legendFormat": "{{pod}}-Receive"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{unique_cluster_name=~\"$Cluster\", image!=\"\", namespace=~\"$Namespace\"}[2m])) by (pod) > 1024*1024",
     "legendFormat": "{{pod}}-Transmit"
    }
   ]
  },
  {
   "title": "CPU Usage In Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\"}[2m])) or on() vector(0)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\"}[2m]))/sum(kube_pod_container_resource_requests{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"}) or on() vector(0)",
     "legendFormat": "Usage/Request(%)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\"}[2m]))/sum(kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"}) or on() vector(0)",
     "legendFormat": "Usage/Limit(%)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"core\", resource=\"cpu\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", resource=\"limits.cpu\", type=\"hard\"} ",
     "legendFormat": "Quota"
    },
    {
     "expr": "sum(sum(kube_node_status_capacity{unique_cluster_name=~\"$Cluster\", resource=\"cpu\"}) by (node) + sum(kube_node_spec_unschedulable{unique_cluster_name=~\"$Cluster\"}==0) by(node)) or on() vector(0)",
     "legendFormat": "Cluster  Available"
    }
   ]
  },
  {
   "title": "Age",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max(kube_namespace_created{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Insight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{unique_cluster_name=~\"$Cluster\", condition=\"false\", namespace=\"$Namespace\"}==1) by(namespace) - (count(kube_pod_status_phase{unique_cluster_name=~\"$Cluster\", phase=\"Succeeded\", namespace=\"$Namespace\"}==1) by(namespace) or vector(0)) or count(kube_pod_status_ready{unique_cluster_name=~\"$Cluster\", condition=\"false\", namespace=\"$Namespace\"}==1) by(namespace)",
     "legendFormat": "NotReady"
    },
    {
     "expr": "count(kube_pod_status_unschedulable{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "UnSchedulable"
    }
   ]
  },
  {
   "title": "Workload Insight",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(kube_deployment_status_replicas_ready{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) by (deployment)<sum(kube_deployment_spec_replicas{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) by (deployment)) or on() vector(0)",
     "legendFormat": "NotReady Deployment"
    },
    {
     "expr": "count(sum(kube_statefulset_status_replicas_ready{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})by(statefulset)<sum(kube_statefulset_replicas{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})by (statefulset)) or on() vector(0)",
     "legendFormat": "NotReady Statefulset"
    },
    {
     "expr": "count(kube_daemonset_status_number_unavailable{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}>0) or on() vector(0)",
     "legendFormat": "NotReady Daemonset"
    },
    {
     "expr": "count(kube_job_status_failed{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"} == 1)",
     "legendFormat": "Failed Job"
    }
   ]
  },
  {
   "title": "Memory Usage In Bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\"})/sum(kube_pod_container_resource_requests{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"}) or on() vector(0)",
     "legendFormat": "Usage/Request(%)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\"})/sum(kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"}) or on() vector(0)",
     "legendFormat": "Usage/Limit(%)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", unit=\"byte\", resource=\"memory\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=~\"$Namespace\", resource=\"limits.memory\", type=\"hard\"}",
     "legendFormat": "Quota"
    },
    {
     "expr": "sum(sum(kube_node_status_capacity{unique_cluster_name=~\"$Cluster\", resource=\"memory\"}) by (node) + sum(kube_node_spec_unschedulable{unique_cluster_name=~\"$Cluster\"}==0) by(node)) or on() vector(0)",
     "legendFormat": "Cluster  Available"
    }
   ]
  },
  {
   "title": "Quota",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_resourcequota_created{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Unbound PVC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_status_phase{unique_cluster_name=~\"$Cluster\", phase!=\"Bound\", namespace=\"$Namespace\"}==1) or on() vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Events(1h)",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_error_total{unique_cluster_name=~\"$Cluster\", namespace='$Namespace'}[1h])) by (kind, name, reason)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning Event Trends",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ceil(sum(increase(eventer_events_warning_total{unique_cluster_name=~\"$Cluster\", namespace='$Namespace'}[1h]))by(kind, reason, name))>0",
     "legendFormat": "{{kind}}/{{name}}/{{reason}}"
    }
   ]
  },
  {
   "title": "Hot Images",
   "type": "table",
   "gridPos": { "h": 20, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sort_desc(sum by(image) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\", resource=\"pods\", type=\"hard\"})",
     "legendFormat": "Quota"
    },
    {
     "expr": "count(kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Deployment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_deployment_created{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "PersistentVolumeClaim",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\", resource=\"persistentvolumeclaims\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "ConfigMap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_configmap_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\", resource=\"configmaps\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "StatefulSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_statefulset_created{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "PVC Storage Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_resource_requests_storage_bytes{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(sum by (persistentvolumeclaim) (kube_persistentvolumeclaim_resource_requests_storage_bytes{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) and group by (persistentvolumeclaim) (kube_persistentvolumeclaim_status_phase{unique_cluster_name=~\"$Cluster\", phase=\"Bound\", namespace=\"$Namespace\"} == 1)) or on() vector(0)",
     "legendFormat": "Bounded"
    }
   ]
  },
  {
   "title": "LoadBalancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_spec_type{unique_cluster_name=~\"$Cluster\", type=\"LoadBalancer\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\", resource=\"services.loadbalancers\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "DaemonSet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_daemonset_created{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_ingress_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})or on() vector(0)",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "Secret",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_secret_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\", resource=\"secrets\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_job_info{namespace=\"$Namespace\"})or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "count(kube_job_status_active{namespace=\"$Namespace\"}==1)or on() vector(0)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Cron Job",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_cronjob_created{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "count(kube_cronjob_status_active{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}==1) or on() vector(0)",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_service_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) or on() vector(0)",
     "legendFormat": "Created"
    },
    {
     "expr": "max(kube_resourcequota{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\", resource=\"services\", type=\"hard\"})",
     "legendFormat": "Quota"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "group by (image, container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() max by (container,pod)(kube_pod_container_status_running{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() max by (container,pod)(kube_pod_container_status_restarts_total{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Restarts"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() max(irate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\",container!=\"\",container!=\"POD\"}[1m])) by (pod,container)"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(irate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", container!=\"\",container!=\"POD\",namespace=\"$Namespace\"}[1m])) by (container,pod) / (max(container_spec_cpu_quota{unique_cluster_name=~\"$Cluster\", container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"}/100000 > 0) by (container,pod)))"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_requests_cpu_cores{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "CPU Request"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(irate(container_cpu_usage_seconds_total{unique_cluster_name=~\"$Cluster\", container!=\"\",container!=\"POD\",namespace=\"$Namespace\"}[1m])) by (container,pod) / (max by (container,pod)(kube_pod_container_resource_requests_cpu_cores{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})))"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\", resource=\"cpu\",namespace=\"$Namespace\"})",
     "legendFormat": "CPU Limit"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() max(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\", container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod,container)"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\", container!=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod,container) / max(container_spec_memory_limit_bytes{unique_cluster_name=~\"$Cluster\", container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod, container) < 1)"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_requests_memory_bytes{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"})",
     "legendFormat": "Memory Request"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() (max(container_memory_working_set_bytes{unique_cluster_name=~\"$Cluster\", container !=\"\",container!=\"POD\",namespace=~\"$Namespace\"}) by (pod,container) / max by (container,pod)(kube_pod_container_resource_requests_memory_bytes{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}))"
    },
    {
     "expr": "group by (container, container_id, pod) (kube_pod_container_info{unique_cluster_name=~\"$Cluster\", namespace=\"$Namespace\"}) * on(container,pod) group_left() sum by (container,pod)(kube_pod_container_resource_limits{unique_cluster_name=~\"$Cluster\", resource=\"memory\",namespace=\"$Namespace\"})",
     "legendFormat": "Memory Limit"
    }
   ]
  }
 ]
}